### PR TITLE
code overflow bug fixed

### PR DESCRIPTION
**Pull request by RamvigneshA**
## What does this PR do?

This PR will fix the html code tag, text overflow issue.

## Issue
Screenshot from 2024-11-28 00-03-28

## Resolved
Screenshot from 2024-11-28 00-02-45

### Issue seen in this following link
[https://appwrite.io/docs/references/cloud/server-nodejs/messaging#createSmtpProvider](url)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Review by RamvigneshA — COMMENTED** [review]
self reviewed

**Comment by RamvigneshA** [comment]
@thejessewinton please review this PR :)

**Comment by thejessewinton** [comment]
@RamvigneshA LGTM!

**Review by Herry0092 — APPROVED** [review]

**Comment by RamvigneshA** [comment]
@thejessewinton @Herry0092 
Hi,
Thanks for your review and approval! I'm excited to see these changes merged.Its my first contribution.. :)

**Pull request merged**
