### PR TITLE
Added Appwrite Authentication in Next.js

### PR DESCRIPTION
**Pull request by Nishantjain10**
Closes https://github.com/appwrite/website/issues/91

This PR is dedicated to creating a deep-dive tutorial aimed at beginners, focused on Appwrite Authentication in depth with Next.js. The tutorial will cover setup, implementation, and provide a functional app with authentication screens.

Content:
The tutorial follows the format in /docs/tutorials/nextjs -auth and includes:

Sign Up
Log In
Verification
Recovery
Conditional Routing
Preferences
Delete Account

Here are the live images, Did not use css and other styles as recommended by @gewenyu99:
image
image
image
image
image
image

### CODE REVIEW

**Comment by gewenyu99** [comment]
@Nishantjain10 lmk when this is ready for review!

**Comment by Nishantjain10** [comment]
> @Nishantjain10 lmk when this is ready for review!

Ok, I will let you know. I was facing some build error, restructuring the tutorial asap.

**Comment by gewenyu99** [comment]
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

**Comment by Nishantjain10** [comment]
> Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship.
> 
> Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

Hey Vincent, here's my discord username: nishant7824

**Pull request closed without merging**
