### PR TITLE
Correct expiry key for setcookie in PHP SSR code samples

### PR DESCRIPTION
**Pull request by dcowan-london**
## What does this PR do?

Corrects the code samples in the SSR docs

## Test Plan

I tested the code samples with a demo project and verified the correct cookies were created.

## Related PRs and Issues

Fixes Issue #721 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by dcowan-london** [comment]
I see the CI test has failed - looking at the logs, I don't think that should have anything to do with the changes I've made?

**Comment by dcowan-london** [comment]
@gewenyu99 Sorry to ping!

**Comment by loks0n** [comment]
> I see the CI test has failed - looking at the logs, I don't think that should have anything to do with the changes I've made?

Can you merge in the latest `main` branch? We can merge after this

**Comment by dcowan-london** [comment]
> > I see the CI test has failed - looking at the logs, I don't think that should have anything to do with the changes I've made?
> 
> Can you merge in the latest `main` branch? We can merge after this

Done!

**Review by gewenyu99 — APPROVED** [review]
Thanks!

**Comment by dcowan-london** [comment]
@gewenyu99 Is this going to be merged sometime soon? I see a bunch of discussion about it on Discord.

**Review by stnguyen90 — APPROVED** [review]
Not sure why the build doesn't work.

I ran it locally and confirmed it looks good:

image

image

**Pull request merged**
