### PR TITLE
fix: Documentation queries mismatch

### LINKED ISSUE #1353: 📚 Documentation: Double check queries
### 💭 Description

The syntax for some queries don't seem to match between the docs and the SDKs.

For example, the Python SDK's has [`Query.and_queries()`](https://github.com/appwrite/sdk-for-python/blob/dba5c5d63e9b426753a73793bf8d734566a44585/appwrite/query.py#L107), but the docs show `Query.and()`:

image

In addition, the Swift SDK requires the `value` label like [`Query.equal("released", value: [true])`](https://github.com/appwrite/sdk-generator/blob/2dd681f3c773b2054f0b28659cf39a1f1649edcf/tests/languages/apple/Tests.swift#L151), but the docs just show `Query.equal("title", ["Iron Man"])`:

image

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by askadityapandey**
## What does this PR do?

fixes #1353 , 

## Test Plan

It's a very minor change, easily visible.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Review by stnguyen90 — COMMENTED** [review]
@askadityapandey, if you're interested in working on an issue, please comment on the issue and asked to be assigned.

Also, the issue was to review all the queries and not just the examples mentioned in the issue.

**Comment by askadityapandey** [comment]
> @askadityapandey, if you're interested in working on an issue, please comment on the issue and asked to be assigned.
> 
> Also, the issue was to review all the queries and not just the examples mentioned in the issue.

Hey @stnguyen90 , thanks for your clarification. I'll take care of asking first from the next time.
Also do you have any suggestion or Idea how can I quickly check all the queries? I mean  I am manually checking right now and I haven't found ```Query.greaterThanEqual``` in Node.Js while it's in Documentation.

**Review by stnguyen90 — COMMENTED** [review]
> Also do you have any suggestion or Idea how can I quickly check all the queries? I mean I am manually checking right now and I haven't found Query.greaterThanEqual in Node.Js while it's in Documentation.

@askadityapandey you can install the SDK and test it out in an IDE. Or you can look at the source code. For example, https://github.com/appwrite/sdk-for-node/blob/7a2418cafaf3cff4247b2e8d9c106e1ab7e9288b/src/query.ts#L108.

**Comment by stnguyen90** [comment]
Closing insufficient and stale PR

**Pull request closed without merging**
