### PR TITLE
hacktoberfest✨

### PR DESCRIPTION
**Pull request by ravi0900**
## What does this PR do?

All changes made by taking care of all 4 breakpoints, (mobile, tab, laptop, desktop)
1. Updated Github Star Count 33.2 to 35.2

2. Few Letter Cases Change to more Professional
a) Go to console -> Go to Console
b) Search in docs -> Search In Docs

I really want to contribute in appwrite and want to part of hacktoberfest2023, I'm a beginner, I spend my whole day understanding this code, and made these smaill changes, please accept my contribution.
Thank you.

## Test Plan

NA
## Related PRs and Issues

#201 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by ravi0900** [comment]
@Haimantika mam please please accept it... tell me if further document I can improve. I spend my whole here setup and searching elements in code.

**Comment by Haimantika** [comment]
> @Haimantika mam please please accept it... tell me if further document I can improve. I spend my whole here setup and searching elements in code.

Hi, I mentioned in the issue that we are going ahead with sentence case, so the PR is not valid. Please look for other issues to contribute. Will be closing the PR.

**Comment by ravi0900** [comment]
@Haimantika, this was heart attacking moment, thanks for closing this PR.

**Comment by tessamero** [comment]
@ravi0900 Keep in mind to search for hacktoberfest labeled issues for the future. It is the same process for all hacktoberfest projects. Thank you for taking the time. We are all learning in this process together.

**Pull request closed without merging**
