### PR TITLE
separated `anonymous` and `magic URL` by comma

### PR DESCRIPTION
**Pull request by PratikDev**
separated `anonymous` and `magic URL` by comma, removed unnecessary space, and made all method names Camal Case

## What does this PR do?

Fixes punctuation issues in the doc so that any readers get a better understanding of the documentation

## Test Plan

No tests necessary

## Related PRs and Issues

Not related to any other PR

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by gewenyu99** [comment]
These aren't proper nouns, so I wouldn't do anything with the casing.

If you could just add the comma and leave the rest alone, would be great ❤️

**Review by gewenyu99 — CHANGES_REQUESTED** [review]
Please remove the case changes and only add a comma.

**Comment by PratikDev** [comment]
did it

**Review by gewenyu99 — APPROVED** [review]
LGTM

**Pull request merged**
