### PR TITLE
Update Copyright year

### PR DESCRIPTION
**Pull request by amanr-dev**
## What does this PR do?

Updated copyright year from 2023 to 2024, Happy New Year.

### CODE REVIEW

**Review by eldadfux — APPROVED** [review]

**Comment by eldadfux** [comment]
Happy new year!

**Comment by michaelparkadze** [comment]
What about a more long term solution?

`<div>Copyright © {new Date().getFullYear()} Appwrite</div>`

instead of:

`<div>Copyright © 2024 Appwrite</div>`

**Comment by amanr-dev** [comment]
Hi there appwrite, 2023 is gone 🙂. Please review the PR.

**Comment by amanr-dev** [comment]
> Hi there appwrite, 2023 is gone 🙂.

Hi @TorstenDittmann, Please review the PR.

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
