### PR TITLE
 Optimize Dockerfile: Reduce Layers and Improve Build Performance

### PR DESCRIPTION
**Pull request by SainiAditya1**
## What does this PR do?
Combined corepack enable, pnpm install, and pnpm run build commands into a single RUN instruction.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
I dont think the build will work like this 🤔

**Comment by SainiAditya1** [comment]
@TorstenDittmann Thanks for the review , please refer to this  article  https://docs.docker.com/develop/develop-images/instructions/ .

**Comment by SainiAditya1** [comment]
@TorstenDittmann , Please Review this.

**Comment by TorstenDittmann** [comment]
> @TorstenDittmann Thanks for the review , please refer to this article https://docs.docker.com/develop/develop-images/instructions/ .

It will still not work like this due to `--mount` 👍🏻

**Pull request closed without merging**
